from github import Github, InputGitTreeElement
import os


def commit_workflow(owner, repo, branch, workflow_content):
    token = os.getenv("GHUB_TOKEN")
    if not token:
        raise RuntimeError("GITHUB_TOKEN environment variable is not set")

    g = Github(token)
    repository = g.get_repo(f"{owner}/{repo}")

    # Get main branch reference
    main_ref = repository.get_git_ref("heads/main")
    sha = main_ref.object.sha

    # Create new branch (if not exists)
    try:
        repository.get_git_ref(f"heads/{branch}")
    except Exception:
        repository.create_git_ref(ref=f"refs/heads/{branch}", sha=sha)

    # Create blob and commit
    path = f".github/workflows/{repo}-ci.yml"
    blob = repository.create_git_blob(workflow_content, "utf-8")
    element = InputGitTreeElement(path=path, mode="100644", type="blob", sha=blob.sha)
    base_tree = repository.get_git_tree(sha)
    tree = repository.create_git_tree([element], base_tree=base_tree)
    commit = repository.create_git_commit("Add CI/CD workflow", tree, [repository.get_git_commit(sha)])
    repository.get_git_ref(f"heads/{branch}").edit(commit.sha)

    return {"commit_url": f"https://github.com/{owner}/{repo}/commit/{commit.sha}", "branch": branch}


def create_pull_request(owner, repo, branch, issue_key=None):
    """Create a Pull Request from the branch into main.
    Optionally include Jira issue key in the title/body.
    """
    token = os.getenv("GHUB_TOKEN")
    if not token:
        raise RuntimeError("GITHUB_TOKEN environment variable is not set")

    g = Github(token)
    repository = g.get_repo(f"{owner}/{repo}")

    title = f"Add CI/CD workflow ({branch})"
    if issue_key:
        title = f"[{issue_key}] " + title

    body = "This PR adds a CI/CD workflow generated by the Copilot Agent.\n"
    if issue_key:
        body += f"Linked Jira issue: {issue_key}\n"


    pr = repository.create_pull(title=title, body=body, head=branch, base="main")
    return {"pr_url": pr.html_url, "pr_number": pr.number}


def create_copilot_issue(owner, repo, issue_key, summary, description):
    """Create a GitHub Issue to trigger Copilot Agent.
    """
    token = os.getenv("GITHUB_TOKEN")
    if not token:
        raise RuntimeError("GITHUB_TOKEN environment variable is not set")

    g = Github(token)
    repository = g.get_repo(f"{owner}/{repo}")

    title = f"[{issue_key}] Fix: {summary}"
    body = (
        f"@copilot please fix this issue based on the following requirements.\n\n"
        f"**Jira Issue**: {issue_key}\n"
        f"**Description**:\n{description}\n"
    )

    # Create the issue
    issue = repository.create_issue(title=title, body=body)

    # Try to assign to copilot if possible (optional, mention in body is primary trigger)
    # Note: explicit assignment might fail if @copilot isn't a "member", but mention works.
    try:
        issue.add_to_assignees("copilot")
    except Exception:
        pass  # Ignore if assignment fails, the mention in body is key.

    return {"issue_url": issue.html_url, "issue_number": issue.number}


def apply_text_patches(owner, repo, base_branch, new_branch, changes):
    """Apply simple text replacements to files and commit on a new branch.

    changes: list of {"path": "relative/file/path", "find": "text", "replace": "text"}
    """
    token = os.getenv("GHUB_TOKEN")
    if not token:
        raise RuntimeError("GHUB_TOKEN environment variable is not set")

    g = Github(token)
    repository = g.get_repo(f"{owner}/{repo}")

    # Get base ref and create new branch from it if missing
    base_ref = repository.get_git_ref(f"heads/{base_branch}")
    base_sha = base_ref.object.sha
    try:
        repository.get_git_ref(f"heads/{new_branch}")
    except Exception:
        repository.create_git_ref(ref=f"refs/heads/{new_branch}", sha=base_sha)

    # Prepare blobs and tree elements for changed files
    elements = []
    for ch in changes:
        path = ch["path"]
        try:
            file = repository.get_contents(path, ref=base_branch)
            content = file.decoded_content.decode("utf-8")
        except Exception:
            raise RuntimeError(f"Cannot read file '{path}' from branch {base_branch}")

        new_content = content.replace(ch.get("find", ""), ch.get("replace", ""))
        blob = repository.create_git_blob(new_content, "utf-8")
        elements.append(InputGitTreeElement(path=path, mode="100644", type="blob", sha=blob.sha))

    # Create tree and commit against current branch tip
    branch_ref = repository.get_git_ref(f"heads/{new_branch}")
    branch_sha = branch_ref.object.sha
    base_tree = repository.get_git_tree(branch_sha)
    tree = repository.create_git_tree(elements, base_tree=base_tree)
    commit = repository.create_git_commit("Apply automated fixes from Jira", tree, [repository.get_git_commit(branch_sha)])
    branch_ref.edit(commit.sha)

    return {"commit_url": f"https://github.com/{owner}/{repo}/commit/{commit.sha}", "branch": new_branch}


def post_pr_comment(owner, repo, pr_number, body):
    """Post a comment on a Pull Request (Issue)."""
    token = os.getenv("GHUB_TOKEN") or os.getenv("GITHUB_TOKEN")
    if not token:
        raise RuntimeError("GITHUB_TOKEN or GHUB_TOKEN environment variable is not set")

    g = Github(token)
    repository = g.get_repo(f"{owner}/{repo}")
    issue = repository.get_issue(pr_number)
    comment = issue.create_comment(body)
    return {"comment_url": comment.html_url, "id": comment.id}
